apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
  labels:
    release: stable
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:  
    - ReadWriteOnce
  hostPath:
    path: /tmp/data