apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:  
    - ReadWriteOnce
  hostPath:
    path: /tmp/data