# FIXME: pvc not bounding to created pv

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
spec:
  accessModes: 
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Ki
  volumeName: demo-pv
  storageClassName: manual