apiVersion: v1
kind: Pod
metadata:
  name: volume-demo-2
spec:
  containers:
  - name: volume-demo-container
    image: busybox:stable
    command: ["/bin/sh", "-c"]
    args: ["while true; do sleep 30; done;"]
    volumeMounts:
    - mountPath: /test-volume
      name: volume-demo-volume
  volumes:
  - name: volume-demo-volume
    hostPath:
      path: /tmp
      type: Directory